gtt-project/redmine_gtt

Gemfile

Redmine (and Redmica) Gemfile `pg` gem version is quite variant, so supporting configurable gem pg version will be necessary, I think.
- Add `GEM_PG_VERSION` environment variable and use it if it is specified.

Configurable gem pg version

---

assets/javascripts/app.js
assets/stylesheets/fonts.css

Fixes #41 .
- Seperates gtt icon namespace using `gtt-icons-` instead of `icons-` which is used by Redmine's icon font

Seperates gtt icon namespace, fixes #41

---

init.rb

- requires Redmine `4.0.0` or higher
- sets release version to `2.1.0`

Prepares for release

---

lib/redmine_gtt/patches/geojson_attribute.rb

Fixes https://github.com/gtt-project/redmine_gtt_print/issues/8#issuecomment-801099567.
- Don't output `crs` property in geometry when calling `ST_AsGeoJSON`.
- About more details, please see https://github.com/gtt-project/redmine_gtt_print/issues/8#issuecomment-801099567 comment.

Fixed missing POI issue in gtt_print plugin

---

app/helpers/gtt_map_helper.rb
src/components/gtt-client.ts
src/stylesheets/app.scss

Fixes #50 .
Fixes #51 .
Fixes #52 .
- use DOMContentLoad event instead of $(document).ready to enable window.onload event.
- raise zoomToExtent() when legend is open, because hidden div can't get width/height.
- delete ol-popup custom css to fix popup position

fixes #50, #51, #52

---

src/@types/window.d.ts
src/components/gtt-client.ts

Signed-off-by: Taro Matsuzawa <btm@tech.email.ne.jp>
Fixes #63 .
- fixes: #63 use status_id to check color
- added missing impliment from app.js
- overwride redmine's replaceIssueFormWith to redraw map in editing mode

fixes 63 and others

---

Gemfile
README.md

Fixes #66.
- Like `pg` version, I supported `rgeo-activerecord` and `activerecord-postgis-adapter` versions with environment variables.
- About each default versions, you can check the following links:
- `rgeo-activerecord`: => 6.2.2
- https://github.com/rgeo/rgeo-activerecord#installation
- https://github.com/rgeo/rgeo-activerecord/releases
- `activerecord-postgis-adapter`: => 5.2.3
- https://github.com/rgeo/activerecord-postgis-adapter#version-7x-supports-activerecord-61
- https://github.com/rgeo/activerecord-postgis-adapter/releases

Supported Gemfile rgeo-activerecord/activerecord-postgis-adapter compatible versions with environment variables

---

app/views/issues/index/_map.html.erb
assets/stylesheets/app.css

- Show the map on issues page by default, Reverts MCR "hack"

Do not hide map by default

---

README.md
config/locales/en.yml
config/locales/ja.yml
lib/redmine_gtt/actions/update_project_settings.rb
lib/redmine_gtt/patches/projects_controller_patch.rb
test/test_helper.rb
test/unit/update_project_settings_test.rb

Fixes #65.
- Show the following error message when updating project geometry with invalid multi polygon
- ![en_error_gtt](https://user-images.githubusercontent.com/629923/113803674-0171f200-9798-11eb-95dd-92a58848af50.png)
- ![ja_error_gtt](https://user-images.githubusercontent.com/629923/113803704-0afb5a00-9798-11eb-95eb-62cdad2d7de1.png)
- When switching to `Project` tab, the error message is also shown on the tab:
- ![en_error_project](https://user-images.githubusercontent.com/629923/113803761-24040b00-9798-11eb-9a33-abce606929da.png)
- ![ja_error_project](https://user-images.githubusercontent.com/629923/113803772-29615580-9798-11eb-9bd6-1104eb057a1d.png)

Show error message when updating project geometry with invalid multi polygon

---

src/components/gtt-setting.ts

Fixes #73 .
- If value is selected, then remove it before appending all available fonts.

Fixed duplicated tracker icon issue

---

src/components/gtt-client.ts

Fixes #75.
- Fix invalid compare condition.

Fixed reload font time error when empty geometry

---

src/components/gtt-client.ts

Fixes #77.
- Appending alpha value (`0.2`) as hexadecimal value (`33`) may be quick and dirty...

Set fill color from tracker status color with alpha 0.2

---

Gemfile
README.md

Supports #82.
- Upgrade gem pg default version from 1.1.4 to 1.2.2.

Upgraded gem pg default version from 1.1.4 to 1.2.2

---

yarn.lock

Fixes https://github.com/gtt-project/redmine_gtt/security/dependabot/yarn.lock/postcss/open.
- Just executed `yarn upgrade css-loader`.

Fixed postcss vulnerability issue by 'yarn upgrade css-loader'

---

package.json
src/components/gtt-client.ts
yarn.lock

Supports #99.
- Upgrade types-ol-ext to the latest released version at [@gtt-project/types-ol-ext](https://www.npmjs.com/package/@gtt-project/types-ol-ext)
- Remove `any` keyword as much as possible.

Upgrading types-ol-ext

---

app/helpers/gtt_map_helper.rb
app/views/redmine_gtt/hooks/_view_issues_form_details_top.html.erb
app/views/settings/gtt/_settings.html.erb
config/locales/en.yml
config/locales/ja.yml
init.rb
src/components/gtt-client.ts

Supports #105.
- Configurable editable geometry types and geojson upload on issue map
- en:  
- ja:  
- Default values are as follows:
- Editable geometry types on issue map: `["Point"]`
- Enable GeoJSON upload on issue map: `false`
- Adjusted en/ja locales:
- Commented out unused words
- Adjusted ja locale

Configurable editable geometry types and geojson upload on issue map

---

lib/redmine_gtt/hooks/view_layouts_base_html_head_hook.rb

I noticed that `geocoder_options` nil case is not checked.
This PR will solve the issue.
- Check `geocoder_options` nil case.

Check geocoder_options nil case

---

lib/redmine_gtt.rb

Fixes #119.
- Limit deface app/overrides path to only gtt plugin

Limit deface app/overrides path to only gtt plugin

---

init.rb
lib/redmine_gtt.rb

Closes #129.
> **Problem**
> Currently, reloading patches timing is only `ActiveSupport::Reloader.to_prepare` which is called before `Rails.configuration.to_prepare` that is often used in other plugins,
> but from the following article and Redmine.org issue, applying Controller patch before Helper patch seems to be the cause of the issue.
> - [The Proper Way to Add a Project Settings Tab for Your Redmine Plugin - Jens Krämer](https://jkraemer.net/2018/05/add-a-project-settings-tab-for-your-redmine-plugin)
> - [Defect #28133: Controller patch causes Helper Patch down - Redmine](https://www.redmine.org/issues/28133)
> 
> **Improvement**
> Separate reloading patches timing to both `ActiveSupport::Reloader.to_prepare` and …

Separate reload patches timing

---

app/helpers/gtt_map_helper.rb
app/views/settings/gtt/_settings.html.erb
config/locales/en.yml
config/locales/ja.yml
init.rb
src/components/gtt-client.ts

Supports #131.
- Configurable geocoding button visibility on map

Configurable geocoding button visibility on map

---

app/overrides/issues.rb
app/overrides/projects.rb

- Adjusted deface override original value and position
This comes from 2.1-stable branch with Redmine 4.2.3 (4.2-stable).

Adjusted deface override original value and position

---

lib/redmine_gtt/patches/issue_query_patch.rb

Fixes #134.
- Just move `Arel.sql` to actual SQL building part, then add explicit type cast of `lng` and `lat` values.
- I confirmed that `RAILS_ENV=test NAME=redmine_gtt bundle exec rake redmine:plugins:test` all passed.

Fixed Brakeman false warning

---

lib/redmine_gtt/patches/projects_controller_patch.rb
test/integration/projects_api_test.rb

Workaround for #145.
- Use projects.json spatial query filter only when having `include=geometry` or `contains=(WKT)` params.
- NOTE: This is just a workaround.
I confirmed that existing all tests passed by the following command.
```bash
bundle exec rake redmine:plugins:test RAILS_ENV=test NAME=redmine_gtt
```

Workaround for projects filter since Redmine >= 4.1

---

db/migrate/20170901085900_change_tile_source_type.rb
db/migrate/20170907013251_add_default_value_to_global_tile_source_field.rb

Fixes #21.
- Fixed ActiveRecord::IrreversibleMigration issue when uninstalling plugin
I referred the following Japanese article to solve the issue.
- [migrationでrollback可否でchangeかup/downを使い分ける - Qiita](https://qiita.com/koni4k/items/294342048cb6d47bcc3f)
Here is the way to confirm the fix.
```sh
bundle exec rake db:drop
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rake redmine:plugins:migrate
bundle exec rake redmine:plugins:test RAILS_ENV=test NAME=redmine_gtt
bundle exec rake redmine:plugins:migrate VERSION=0 NAME=redmine_gtt
```

Fixed ActiveRecord::IrreversibleMigration issue when uninstalling plugin

---

lib/redmine_gtt/patches/projects_controller_patch.rb

Fixes #149 .
- hook AbstractController::ActionNotFound error with action_missing and call update_gtt_configuration

#149 use action_missing to call update_gtt_configuration with Zwitwerk in production mode

---

init.rb
lib/redmine_gtt/patches/issue_patch.rb
test/unit/issue_test.rb

Fixes #161.
- Flatten geojson coordinates before array length comparison
The error happened when new coordinates length > old coordinates length in polygon and Array.zip generate nil when latter (old) has missing values, so I just moved flattern coordinates part before coordinates array length comparison.
- https://docs.ruby-lang.org/ja/latest/class/Array.html#I_ZIP

Flatten geojson coordinates before array length comparison

---

app/controllers/gtt_tile_sources_controller.rb
test/functional/gtt_tile_sources_controller_test.rb

Fixes #173.
- Fix `gtt_tile_sources` view's `create_and_continue` button action
- Referred redmine core groups controller create action part:
- https://github.com/redmine/redmine/blob/master/app/controllers/groups_controller.rb#L75
```rb
redirect_to(params[:continue] ? new_group_path : groups_path)
```
- Add functional test code
- Referred redmine core groups controller functional test part:
- https://github.com/redmine/redmine/blob/master/test/functional/groups_controller_test.rb#L122-L137

Fix "gtt_tile_sources" view's "create_and_continue" button action (#173)

---

src/stylesheets/app.scss

Fixes #163.
- Fix LayerSwitcher label style
- Redmine itself `.tabular label` style is defined here:
- https://github.com/redmine/redmine/blob/master/public/stylesheets/application.css#L841-L850
```css
.tabular label{
font-weight: bold;
float: left;
text-align: right;
/* width of left column */
margin-left: -180px;
/* width of labels. Should be smaller than left column to create some right margin */
width: 175px;
line-height: 24px;
}
```
- Disable above styles for issue's field label one by resetting (=`initial`) each css properties.
- Adjust other `.ol-control button(:hover)` part formatting.

Fix LayerSwitcher label style (#163)

---

app/views/projects/show.api.rsb
lib/redmine_gtt/patches/projects_helper_patch.rb
test/integration/projects_api_test.rb

Supports #172.
~~**NOTE: I will check whether this change will not affect other existence projects, so please wait for a while.**~~
=> I confirmed this on the other existence project.
- Support `include=layers` for projects index/show api
- Delete previous changes (https://github.com/gtt-project/redmine_gtt/commit/273b93a7954ffa92aa3f23ab04ead1abb9ca26e5) to supports both index and show api with better way.
- Modify JSON property name from `gttLayer` to `layers` to match other filters/properties convention.
- https://github.com/redmine/redmine/blob/master/app/helpers/projects_helper.rb#L144-L174
- Add test for projects index/show api  

Support 'include=layers' for projects index/show api (#172)

---

.github/workflows/test-postgis.yml

Fixes #205
- Fix CI matrix ruby:3 version by quote.
- Please see: https://github.com/actions/runner/issues/849
I will fix other plugin's CI setting as well, later.

Fix CI matrix ruby:3 version

---

app/views/issues/index.api.rsb
app/views/issues/show.api.rsb
app/views/projects/index.api.rsb
app/views/projects/show.api.rsb
app/views/users/index.api.rsb
app/views/users/show.api.rsb
test/integration/issues_api_test.rb
test/integration/projects_api_test.rb
test/integration/users_api_test.rb

Fixes #203, #171.
- projects index/show **json** api returns `geojson` property as JSON object.
- projects index/show **xml** api returns `geojson` property as string.
- `geojson` property's empty value changed from `""` to `null`.
- Apply same logic to other issues/users api `geojson` property.
Note that existence API clients needs to be updated.

Fix projects/issues/users index/show api to return json object correctly

---

config/locales/ja.yml

Translations update from [OSGeo Weblate](https://weblate.osgeo.org) for [GTT Project/Redmine GTT core plugin](https://weblate.osgeo.org/projects/gtt-project/redmine_gtt/).
Current translation status:

Translations update from OSGeo Weblate

---

app/views/issues/index/_map.html.erb
assets/javascripts/app.js

- ~~Remove `MutationObserver` which is not used.~~
- ~~`ResizeObserver` works instead of that, so actually, `MutationObserver` is not necessary.~~
- => There was different behavior between `2.1-stable` and `main` branch, so I recovered this with fixing condition.
- Remove `toggleAndLoadMap` method which causes unstable expand location in issues index view.
- Use Redmine `toggleFieldset` event handler as fieldset's `onclick` handler.

Fix unstable expand location in issues index view

---

app/views/issues/index/_map.html.erb
src/components/gtt-client/init/events.ts
src/components/gtt-client/openlayers/index.ts

@otsuka This is equivalent of #236 for `next` branch,
> Changes proposed in this pull request:
> - ~~Remove `MutationObserver` which is not used.~~
>   - ~~`ResizeObserver` works instead of that, so actually, `MutationObserver` is not necessary.~~
>   - => There was different behavior between `2.1-stable` and `main` branch, so I recovered this with fixing condition.
> - Remove `toggleAndLoadMap` method which causes unstable expand location in issues index view.
> - Use Redmine `toggleFieldset` event handler as fieldset's `onclick` handler.
but I noticed that original issue happen again when `Default collapsed issues page map` is true.
I will check the cause of the difference.

Fix unstable expand location in issues index view for next

---

config/locales/en.yml
config/locales/ja.yml

- Sync Japanese translation with English for v5.
- Clean up and set same order with English.
@smellman @mopinfish
Could you check whether the following last commit's Japanese translations are valid ?
- https://github.com/gtt-project/redmine_gtt/pull/243/commits/0e22e03da99fa2637a7ee1f1a403004acb29c959
---
@dkastl 
I fixed the `en.yml` comment typo in the following commit.
- https://github.com/gtt-project/redmine_gtt/pull/243/commits/352987dd42613567920ed4f073981f54419940a2

Update Japanese translation for v5

---

app/views/projects/settings/_gtt.html.erb

- Fix project view localization for map layers selection.
Before:
After:

Fix project setting view localization

---

assets/javascripts/app.js

- Fix WKT parse error in history by improving regexp WKT pattern
- Sync from `main` branch latest pattern https://github.com/gtt-project/redmine_gtt/blob/main/src/components/gtt-client/helpers/index.ts#L239 from past fixes:
- https://github.com/gtt-project/redmine_gtt/commit/3470faf31865e635ecdb2c9480838f54b7bc2b88
- https://github.com/gtt-project/redmine_gtt/commit/43fe9ed7e2414766a31de2f745be2b0d500dab9e
- :

Fix WKT parse error in history

---

app/views/redmine_gtt/hooks/_view_issues_form_details_top.html.erb
lib/redmine_gtt/patches/issue_patch.rb

- Support `edit_own_issues` permission from Redmine >= 4.1
- [Feature #1248: New Permission: Edit own issues - Redmine](https://www.redmine.org/issues/1248)
- Use `issue.attributes_editable?` method to detect whether issue is editable.
- https://github.com/redmine/redmine/blob/master/app/models/issue.rb#L195-L200
- TODO: test

Support edit_own_issues permission for issue geometry editing

---

src/components/gtt-client/init/layers.ts

Fixes #254 .
- map icons to be front

#254 map icons to be front

---

.github/workflows/test-postgis.yml

- Manage build matrix settings at a single place (organisation variables): https://github.com/organizations/gtt-project/settings/variables/actions

Uses organisation variables for matrix config

---

.github/workflows/test-postgis.yml

Fixes #271 .
- Use newer `activerecord-postgis-adapter` for redmine master (rails 7.1)

Use newer activerecord-postgis-adapter for redmine master (rails 7.1)

---

db/migrate/20240408062313_remove_gtt_map_layer_position_default.rb

Fixes #274.
- Fix GttMapLayer position default (`0` to `nil`)
Explanation:
1. `acts_as_positioned` is defined in the following Redmine core side, and `before_save` - `set_default_position` assumes that position default is `nil`.
* https://github.com/redmine/redmine/blob/5.1-stable/lib/redmine/acts/positioned.rb#L35-L44
```rb
def acts_as_positioned(options = {})
class_attribute :positioned_options
self.positioned_options = {:scope => Array(options[:scope])}
send :include, Redmine::Acts::Positioned::InstanceMethods
before_save :set_default_position
after_save :update_position
after_destroy :remove_position
end
```
* https://github.com/redmine/redmine/blob/5.1-stable/lib/redmine/acts/positioned.rb#L72-L76
```rb
def set_default_position
if position.nil? …
```

Fix GttMapLayer position default (0 to nil)

---

app/views/issues/show.api.rsb
app/views/issues/show/_map.html.erb
app/views/settings/gtt/_general.html.erb
config/locales/en.yml
config/locales/ja.yml
init.rb
yarn.lock

Fixes #279 .
- Adds plugin settings (see issue screenshot)
- Hides issue map when there is no geometry (and enabled in settings)
- Shows a "nodata" notification box
- Minor change for Show issue API, checking for `@issue.geom`

Adds settings to hide issue map without geometry, fixes #279

---

config/locales/de.yml
config/locales/en.yml
config/locales/ja.yml
lib/redmine_gtt/patches/issue_patch.rb
src/components/gtt-client/helpers/index.ts
src/components/gtt-client/openlayers/index.ts

Fixes #282 .
- Adds a control button to the edit toolbar to clear the map
- Call updateForm to clear the form field
See issue for screenshot.

Adds a control button to clear the map

---

config/locales/de.yml
config/locales/en.yml
config/locales/ja.yml
src/components/gtt-client/geocoding/SearchFactory.ts
src/components/gtt-client/init/controls.ts

Fixes #304
- Use notification box for reverse geocoding

Use notification box for reverse geocoding

---

config/locales/de.yml
config/locales/en.yml
config/locales/ja.yml
src/components/gtt-client/helpers/platforms.ts
src/components/gtt-client/openlayers/index.ts

Fixes #310 .
- Adds a new control button `Edit`
- Enables vertex and line snapping
- Inform the user about `ALT+<click>` shortcut to delete a vertex. 
- Provides a delete button through tooltip
- Draws existing features temporarily light gray when adding a new feature

Improved editor control

---

.github/workflows/test-postgis.yml
app/helpers/gtt_map_helper.rb
app/views/redmine_gtt/hooks/_view_issues_form_details_top.html.erb
test/integration/issues_test.rb
test/system/issues_map_test.rb

Fixes #268 .
- Fixes rotation issue
- Fixes access to `@project`
@dkastl @smellman 
I added the followings:
- Adds integration/system tests
- Fixes the following error in #268 description.
- > With this change the map will not initialize correctly when the project change triggers a dynamic loading of content.

Fixes `/issues/new` map_rotation issue

---

package.json
yarn.lock

Fixes the following error.
https://github.com/sanak/redmine_gtt/actions/runs/10280544083/job/28448110645#step:8:53  
```
ERROR in ./node_modules/ol-ext/interaction/Hover.js 2:0-45
Module not found: Error: Can't resolve '../util/element' in '/__w/redmine_gtt/redmine_gtt/redmine/plugins/redmine_gtt/node_modules/ol-ext/interaction'
Did you mean 'element.js'?
BREAKING CHANGE: The request '../util/element' failed to resolve only because it was resolved as fully specified
```
- To avoid above error for CI test before PR:#330 will be merged.
@dkastl
I think that you are waiting for ol-ext next release (4.0.22) which includes your [PR](https://github.com/Viglino/ol-ext/pull/1090), but now CI is failing (like on my fork …

Limit ol-ext version to 4.0.18 and update yarn.lock

---

app/views/projects/settings/_gtt.html.erb

@mopinfish 
`2.2-stable` ブランチ上で、プロジェクト設定のGTTタブのタイルソースドロップダウンリストのラベルが未翻訳(`Gtt tile source ids`)となっていることを確認したので、日本語訳が適用されるよう、修正しました。
お手すきの際に確認をお願いします。
| 修正前 | 修正後 |
|--------|--------|
| ![before-tilesource-label-fix](https://github.com/user-attachments/assets/97382c49-b311-45f6-a7a2-91c8e1d65506) | ![after-tilesource-label-fix](https://github.com/user-attachments/assets/3de4d332-2c05-4288-9078-b19de56d3b26) |

Fix project settings tilesource label

---

lib/redmine_gtt/patches/geometry_as_custom_field_patch.rb

@mopinfish こちらですが、以下の松澤さんの対応を `2.2-stable` ブランチにも当てるようにします。
(私の方でローカル環境で動作確認済みのため、マージまで進めてしまいます。 🙇‍♂️)
* [export pdf function raise error · Issue #222 · gtt-project/redmine_gtt](https://github.com/gtt-project/redmine_gtt/issues/222)
* [added missing full_text_formatting? method by smellman · Pull Request #223 · gtt-project/redmine_gtt](https://github.com/gtt-project/redmine_gtt/pull/223)

#222 added missing full_text_formatting? method

---

init.rb
package.json
src/styles/icons/custom/custom-icons-def.ts
src/styles/index.ts

Fixes #347 
I'm directly merging this into `main` to avoid yet another PR.

Ensure icons are added to assets

---

app/overrides/issues/show.rb
app/overrides/projects/show.rb

- Fix deface overrides warnings by adjusting deface `:original` hash value.
- https://github.com/spree/deface?tab=readme-ov-file#optional
- > :original - Either a string containing the original markup that is being overridden, or a string that is the SHA1 digest of the original markup. If supplied Deface will log when the original markup changes, which helps highlight overrides that need attention when upgrading versions of the source application. Only really warranted for :replace overrides. NB: All whitespace is stripped before comparison. To generate the SHA1 digest do: Digest::SHA1.hexdigest(original_markup_string.gsub(/\s/, ''))
I will merge this by myself, because this is just fixing warnings in `2.2-stable` branch. (CC: @mopinfish)

[2.2-stable] Fix deface overrides warnings
