gtt-project/redmine_gtt

- README.md
Fixes #35 .
- adding note for postgis adapter to fix rgeo error
> added note for postgis adapter #35

- assets/stylesheets/fonts.css
Fixes https://github.com/hyakumori/redmine_theme_farend_bleuclair/issues/1
- There was a problem with icon fonts 
> Fixes icon font theme issue

- assets/javascripts/app.js
Fixes #38.
- To avoid empty map, force to call `zoomToExtent` method after `ol.Map` loaded, once.
- To avoid Firefox invalid font icon, refresh `Features` layer after detecting that the fonts are loaded.
- Link: [javascript - How to be notified once a web font has loaded - Stack Overflow](https://stackoverflow.com/questions/5680013/how-to-be-notified-once-a-web-font-has-loaded/32292880#32292880)
> Fixed empty map and invalid font (on Firefox) issues

- app/helpers/gtt_map_helper.rb
- app/views/projects/settings/_gtt.html.erb
- app/views/redmine_gtt/hooks/_user_map.html.erb
- app/views/redmine_gtt/hooks/_view_issues_form_details_top.html.erb
- lib/redmine_gtt/patches/issue_patch.rb
- src/components/gtt-client.ts
Fixes #59.
Still needs to check multiple polygon case.
- :
> Made inverse polygon consistent

- package.json
Increases the version number in `package.json` ... which was always forgotten.
> Increases version number

- src/components/gtt-client.ts
> Fixed empty map on issue/new view when changing tracker/status/project

- src/components/gtt-client.ts
Fixes #93.
- Supported XYZ tile source.
> Fixed XYZ tile issue

- src/components/gtt-client.ts
Fixes #106.
- Fixed geolocation error.
> Fixed geolocation error

- lib/redmine_gtt/hooks/view_layouts_base_html_head_hook.rb
Fixes #123.
- Fixed missing geocoder_options argument
> Fixed missing geocoder_options argument

- app/views/gtt_tile_sources/_form.html.erb
- config/locales/en.yml
- config/locales/ja.yml
Fixes #152.
- Adds type selector
- Adds example loader
> Adds selector and examples

- README.md
- doc/api.md
- init.rb
> Prepares 4.1 release

- README.md
@mbasa @nobnisai (CC: @dkastl)  
I added your names in `README.md` - `Authors` section from #102 and #156, so please check this changes.
> Updated README.md - Authors section

- .github/workflows/test-postgis.yml
- app/views/issues/index.api.rsb
- app/views/issues/show.api.rsb
- app/views/projects/index.api.rsb
- app/views/projects/show.api.rsb
- app/views/users/index.api.rsb
- app/views/users/show.api.rsb
@sanak @smellman , I realized that API endpoint changes in upstream Redmine have not been applied for some time, because this plugin completely replaces these endpoints to add the geometry information.
This pull request brings these API endpoints up-to-date:
- Issues
- Projects
- Users
> Updates API endpoints

- .github/workflows/test-postgis.yml
- Update CI matrix from the latest versions
- https://www.redmine.org/projects/redmine/wiki/RedmineInstall
- https://github.com/postgis/docker-postgis
- Remove `master` branch trigger in CI
> Update CI matrix

- .gitignore
- Gemfile
- README.md
- app/views/gtt_tile_sources/_form.html.erb
- config/locales/de.yml
- config/locales/en.yml
- config/locales/ja.yml
- package.json
- src/components/gtt-client.ts
- src/components/gtt-setting.ts
- tsconfig.json
- webpack.config.js
- yarn.lock
Fixes #97  .
- Adds support for vector tiles
> Vector tiles support

- config/locales/de.yml
- config/locales/ja.yml
Translations update from [OSGeo Weblate](https://weblate.osgeo.org) for [GTT Project/Redmine GTT core plugin](https://weblate.osgeo.org/projects/gtt-project/redmine_gtt/).
Current translation status:
> Translations update from OSGeo Weblate

- package.json
- yarn.lock
- Upgrades OpenLayers and OL Mapbox Style
- Upgrades other dependencies
I checked OpenLayers upgrade notes but it doesn't seem to affect this plugin: https://github.com/openlayers/openlayers/blob/v8.1.0/changelog/upgrade-notes.md
> Updates OL and other libraries

- app/helpers/gtt_map_helper.rb
Fixes #257 .
- use observer to change dom event.
> fix map blank bug 257

- src/components/gtt-client/init/layers.ts
- added applyBackground to set background color.
-
-
> use applyBackground to set background color

- src/styles/scss/app.scss
> fix colors on attributions

- .github/workflows/test-postgis.yml
- app/views/gtt_map_layers/_form.html.erb
- package.json
- src/components/gtt-client/init/layers.ts
- yarn.lock
- Updates to OpenLayers 9.0
- Supports Google source (with example)
Unresolved issues:
- Google source seems to have issues with the layer mask.
> OpenLayers 9.0 and Google support

- config/locales/ja.yml
Update #283 .
- Update Japanese translation
-
-
> #283 added Japanese translation message

- config/locales/ja.yml
Update #284 .
- update config/locales/ja
-
-
> #284 update config/locales/ja

- src/components/gtt-client/openlayers/index.ts
- src/styles/scss/app.scss
Fixes #312
- Use `PopupFeature` overlay for better handling of position and style
> Improve feature popups

- package.json
- src/components/gtt-client/init/events.ts
- yarn.lock
Fixes #320 .
- Extends `handleEditIcon` function to also handle "Quote" links
- Increases timeout to 500ms
> Fixes zoom to feature issue when clicking "Quote" link

- config/locales/ja.yml
> Update Japanese locale

- app/helpers/gtt_map_helper.rb
Fixes # .
- fix regression: render 2 maps when change status in editing view.
-
-
> fixes: render 2 maps when change status in editing view

- .github/workflows/test-postgis.yml
- app/views/gtt_map_layers/index.html.erb
Supports Redmine 5 in #338.
- Supports Redmine 5 in #338.
- Update CI to support Redmine 6
Local CI test results are here:
https://github.com/sanak/redmine_gtt/actions/runs/11876926686
> Support Redmine 5

- app/views/redmine_gtt/hooks/_view_layouts_base_html_head.html.erb
- package.json
- src/styles/icons/custom/custom-icons-def.ts
- src/styles/icons/custom/custom-icons.scss
- src/styles/icons/material-design/material-design-def.ts
- src/styles/index.ts
- webpack.config.js
- yarn.lock
Fixes #342 
- Uses `RAILS_ASSET_URL` in CSS
- Removes font loading work-around
- Resolves custom font loadiung security issue
> Improves font icon handling

- lib/redmine_gtt/patches/issue_patch.rb
- Fix update geom nil issue to support customized plugin's system test.
- This is partial commit of the following for #282
- https://github.com/gtt-project/redmine_gtt/commit/e391afa1c829c11c7e09d68909de3c3ae86db567#diff-a1db42ad9f3b0f6fbea6f8853b80add55af7e019c2586e95e40eec97095610d0
This is obvious fix, so I will merge this.
> [2.2-stable] Fix update geom nil issue
